= List of administrators of ee-central.io

Currently does not list all administrators, the list is being completed to match reality.

If you are already an admin or you want to volunteer as an admin, send a pull request with your info in the table below.

[options="header"]
|===
| Name | Roles | Contact
| Ondrej Mihályi | Documentation | Twitter: https://twitter.com/OMihalyi[@omihalyi], Github: https://github.com/OndrejM[@OndrejM], Other: https://itblog.inginea.eu[Blog]
| Alex Theedom | Google Group Mod/Content Provider | Twitter: https://twitter.com/readlearncode[@readlearncode], Github: https://github.com/readlearncode[@readlearncode], Other: https://www.readlearncode.com[Blog]
| Martijn Verburg | Documentation, Github, Mailing List, Slack | Twitter: https://twitter.com/karianna[@karianna], Github: https://github.com/karianna[@karianna]
|===

List of resources which administrators should have access to:
 - write and invite priviledges to the Google Drive (owned by Ondrej Mihályi, but any one can invite others to have the same privileges)
 - write access to the jcpevangelist github repositories (the github org is owned by Tomitribe)
 - admin of the mailing list
 - invited to the slack channel
